const FETCH_PARENT_SUCCESS = "FETCH_PARENT_SUCCESS";
const FETCH_PARENT_FAILED = "FETCH_PARENT_FAILED";
const FETCH_PARENT_REQUEST = "FETCH_PARENT_REQUEST";


export { 
    FETCH_PARENT_REQUEST, 
    FETCH_PARENT_SUCCESS,
    FETCH_PARENT_FAILED,
    };