const FETCH_CHILD_SUCCESS = "FETCH_CHILD_SUCCESS"
const FETCH_CHILD_FAILED = "FETCH_CHILD_FAILED"
const FETCH_CHILD_REQUEST = "FETCH_CHILD_REQUEST"



export {FETCH_CHILD_REQUEST,FETCH_CHILD_SUCCESS,FETCH_CHILD_FAILED};