const FETCH_TOKEN_SUCCESS = "FETCH_TOKEN_SUCCESS"
const FETCH_TOKEN_FAILED = "FETCH_TOKEN_FAILED"
const FETCH_TOKEN_REQUEST = "FETCH_TOKEN_REQUEST"


export {FETCH_TOKEN_REQUEST,FETCH_TOKEN_SUCCESS,FETCH_TOKEN_FAILED};