const FETCH_CHILDPROFILE_SUCCESS = "FETCH_CHILD-PROFILE_SUCCESS"
const FETCH_CHILDPROFILE_FAILED = "FETCH_CHILD-PROFILE_FAILED"
const FETCH_CHILDPROFILE_REQUEST = "FETCH_CHILD-PROFILE_REQUEST"


export {FETCH_CHILDPROFILE_SUCCESS,FETCH_CHILDPROFILE_FAILED,FETCH_CHILDPROFILE_REQUEST};