const FETCH_ENROLLMENT_SUCCESS = "FETCH_ENROLLMENT_SUCCESS"
const FETCH_ENROLLMENT_FAILED = "FETCH_ENROLLMENT_FAILED"
const FETCH_ENROLLMENT_REQUEST = "FETCH_ENROLLMENT_REQUEST"


export {FETCH_ENROLLMENT_REQUEST,FETCH_ENROLLMENT_SUCCESS,FETCH_ENROLLMENT_FAILED};