const FETCH_PARENT_PROFILE_SUCCESS = " FETCH_PARENT_PROFILE_SUCCESS";
const FETCH_PARENT_PROFILE_FAILED = "FETCH_PARENT_PROFILE_FAILED";
const FETCH_PARENT_PROFILE_REQUEST = "FETCH_PARENT_PROFILE_REQUEST";

export { 
    FETCH_PARENT_PROFILE_SUCCESS, 
    FETCH_PARENT_PROFILE_FAILED,
    FETCH_PARENT_PROFILE_REQUEST  };